config/routes.rb
Rails.application.routes.draw do
  root 'places#index'
  get 'about', to: 'pages#about'
  get 'pricing', to: 'pages#create'
  resources :places
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def create
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Companywebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar sticky-top navbar-light bg-light">
  <div class="row">
   <div class="col">
    <a class="navbar-brand" href="/">CompanyWebsite</a>
   </div>
   <div class="col-md-auto links">
    <%= link_to 'About Us', about_path %>
   </div>
   <div class="col col-lg-2">
    <%= link_to 'Pricing', pricing_path %>
   </div>
  </div>

</nav>



    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>

app/views/pages/create.html.erb
<h1>Pricing</h1>

app/views/places/index.html.erb
<div class="hero">
<br />
  <div class="frosty col-10 offset-1 text-center">
    <h1>Find the perfect place,</h1>
    <h2>for your loved ones.</h2>
    <br />
    <%= link_to 'Learn More', about_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/places/new.html.erb
<h1>Add Inquiry</h1>